DOMAIN = "control_my_spa"
VERIFY_SSL = True
TEST_MODE = None
#TEST_MODE = "Data02"
#TEST_MODE = "Data03"
TEST_SPAOWNER = False

UPDATE_INTERVAL_SECONDS_KEY = "update_interval_seconds"
LEGACY_UPDATE_INTERVAL_MINUTES_KEY = "updateintervalminutes"
DEFAULT_UPDATE_INTERVAL_SECONDS = 60
MIN_UPDATE_INTERVAL_SECONDS = 10
MAX_UPDATE_INTERVAL_SECONDS = 180
UPDATE_INTERVAL_STEP_SECONDS = 10
